bottlesdevs/components

index.json
runners/wine/Wine-6.9-GE-2-Alpha.json
runners/wine/lutris-ge-6.9.json

https://github.com/bottlesdevs/Bottles/issues/302

Add Wine-6.9-GE-2 Alpha

---

runners/proton/Proton-6.10-GE-1.json
runners/wine/lutris-6.10.json

Closes https://github.com/bottlesdevs/components/issues/24

Add Proton 6.10 GE and Lutris 6.10 runners

---

index.yml
runners/proton/GE-Proton7-21.yml
runners/proton/GE-Proton7-22.yml
runners/proton/GE-Proton7-23.yml
runners/proton/GE-Proton7-24.yml

Added new GE-Proton versions (21-24)

Added new GE-Proton versions (21-24)

---

index.yml
runners/wine/lutris-ge-7.14-GE-1-LoL.yml
testing.yml

Fixes #(issue)
The game works super well, but in flatpak it requires a custom version of flatpak (which I'm using to do the screenshot). 
https://github.com/flathub/net.lutris.Lutris/issues/85#issuecomment-851544081

Add lutris-ge-7.14

---

dxvk/dxvk-async-1.10.3.yml
index.yml

add dxvk-async 1.10.3

---

index.yml
runners/wine/wine-ge-7-25.yml
runners/wine/wine-ge-7-26.yml
runners/wine/wine-ge-7-27.yml

This PR updates the Wine GE runners.

Add Wine-GE 7.25, 7.26 and 7.27

---

index.yml
runners/wine/lutris-ge-lol-7.0-5.yml

Add lutris-ge-lol-7.0-5 runner

---

runners/proton/GE-Proton7-34.yml
runners/proton/GE-Proton7-35.yml

Added Proton 34 and 35 to Runners
Fixes #(issue)
- [X ] New component
- [ X] Yes

Proton GE 34 and 35

---

.github/pull_request_template.md

This PR will change the PR Template formatting to the following below:
---

Update PR template formatting

---

index.yml
runners/wine/wine-ge-7-33.yml

Support the new release of Wine-GE: https://github.com/GloriousEggroll/wine-ge-custom/releases/tag/GE-Proton7-33

Add Wine-GE-Proton7-33

---

index.yml
runners/wine/kron4ek-wine-7.20-amd64.yml
runners/wine/kron4ek-wine-7.20-staging-amd64.yml
runners/wine/kron4ek-wine-7.20-staging-tkg-amd64.yml
runners/wine/kron4ek-wine-7.20-staging-tkg-x86.yml
runners/wine/kron4ek-wine-7.20-staging-x86.yml
runners/wine/kron4ek-wine-7.20-x86.yml

add kron4ek 7.20 runners

---

index.yml
runners/wine/wine-ge-7-34.yml

This new release brings improvements for EA App from recent Proton Experimental patches

add new wine-ge-7-34

---

index.yml
runners/proton/GE-Proton7-38.yml
runners/proton/GE-Proton7-39.yml

Added GE-Proton7-38/39

---

index.yml
latencyflex/latencyflex-v0.1.1.yml

"This is a maintenance release, fixing compatibility with Vulkan 1.3 drivers."

Add latencyflex 0.1.1

---

runners/wine/wine-ge-proton7-1.yml
runners/wine/wine-ge-proton7-10.yml
runners/wine/wine-ge-proton7-11.yml
runners/wine/wine-ge-proton7-12.yml
runners/wine/wine-ge-proton7-13.yml
runners/wine/wine-ge-proton7-14.yml
runners/wine/wine-ge-proton7-15.yml
runners/wine/wine-ge-proton7-16.yml
runners/wine/wine-ge-proton7-17.yml
runners/wine/wine-ge-proton7-18.yml
runners/wine/wine-ge-proton7-19.yml
runners/wine/wine-ge-proton7-20.yml
runners/wine/wine-ge-proton7-21.yml
runners/wine/wine-ge-proton7-22.yml
runners/wine/wine-ge-proton7-23.yml
runners/wine/wine-ge-proton7-24.yml
runners/wine/wine-ge-proton7-25.yml
runners/wine/wine-ge-proton7-26.yml
runners/wine/wine-ge-proton7-27.yml
runners/wine/wine-ge-proton7-28.yml
runners/wine/wine-ge-proton7-29.yml
runners/wine/wine-ge-proton7-31.yml
runners/wine/wine-ge-proton7-32.yml
runners/wine/wine-ge-proton7-33.yml
runners/wine/wine-ge-proton7-34.yml
runners/wine/wine-ge-proton7-5.yml
runners/wine/wine-ge-proton7-6.yml
runners/wine/wine-ge-proton7-7.yml
runners/wine/wine-ge-proton7-8.yml
runners/wine/wine-ge-proton7-9.yml

My fault, I forgot to commit this into #182

Fix install of wine-ge

---

.github/workflows/pull-components.yml

https://github.com/softprops/action-gh-release/pull/275 got merged upstream, it is now up to date

Use upstream action-gh-release

---

.github/workflows/pull-components.yml

Replace actions-download-asset by Github CLI

---

.github/workflows/pull-components.yml

Following the discussion in https://github.com/bottlesdevs/components/issues/193

Use GITHUB_TOKEN instead of PAT

---

.github/workflows/pull-components.yml
input_files/14-dxvk.yml
input_files/3-soda.yml

An attempt to : 
- Fix the download of vkd3d-proton (release)
- Fix the folder structure of experimental builds
It's an attempt because since the last update, I cannot test components locally anymore, it fails with : 
```
(ERROR) Could not get index for components repository: (37, "Couldn't open file /path/to/components/2022.12.14.yml") 
```
And if I create the yml file by copying it from index.yml, it fails with : 
```
(ERROR) Could not get index for components repository 
```
In both cases, no components are shown in bottles
closes https://github.com/bottlesdevs/components/issues/203

Attempt to fix the CI

---

index.yml
input_files/5-wine-GE-Proton.yml
input_files/7-lutris-ge.yml
runners/wine/lutris-ge-7.0-GE-1-LoL.yml
runners/wine/lutris-ge-7.14-GE-1-LoL.yml
runners/wine/lutris-ge-lol-7.0-5.yml
runners/wine/lutris-ge-lol-7.0-8.yml

Because of League's deprecation of 32-bit clients, all versions released before patch 13.7 are broken.  
Since those custom builds aim only to run League they became obsolete.
I am also adding 7.0-8 because 8.7.1 isn't working for everyone
- Remove all versions prior to patch 13.7
- Add 7.0-8
There are more details in [this post](https://www.reddit.com/r/leagueoflinux/comments/12cei7t/patch_137_feedback_megathread_transition_to_64bit/)
- [] No
Here's the test output:
```
$ LOCAL_COMPONENTS=$HOME/Desktop/components flatpak run com.usebottles.bottles
09:54:49 (INFO) Bottles Started! 
09:54:51 (INFO) Using local components repository at /home/gurja/Desktop/components 
09:54:52 (INFO) Catalog components loaded 
09:54:52 (INFO) Performing Bottles checks… 
09:54:52 (INFO) Dxvks found:
- …
```

Fix lutris-ge-lol versions

---

input_files/11-kron4ek.yml

Fix kron4ek builds

---

.github/workflows/pull-components.yml
51.6.yml
index.yml
input_files/1-runtime.yml
runtimes/runtime-0.6.3.yml

Integrate https://github.com/bottlesdevs/runtime pulling to the CI

Automate runtime pulling

---

.github/workflows/pull-components.yml

Title. The artifact structure has changed in DXVK upstream, this PR adapts for the new structure.

Fix dxvk unstable builds
